In [8]:
import numpy as np
n1=np.random.rand(5) # [0,1)
n1

array([0.45249002, 0.89526094, 0.61471321, 0.36637889, 0.76497585])

In [9]:
n2=np.random.rand(2,4)
n2

array([[0.67161086, 0.37074654, 0.03041248, 0.50875594],
       [0.32997572, 0.66579797, 0.85052166, 0.57538264]])

In [10]:
# 用于从正态分布中返回随机生成的数组
n3=np.random.randn(3)
n3

array([ 2.94472515, -0.35575801, -0.70934351])

In [11]:
n3=np.random.randn(3,4)
n3

array([[ 0.2272723 , -0.01933957,  1.13212268,  0.26008903],
       [ 0.56440624, -1.11003953, -0.97231461, -0.96546423],
       [-0.11786281,  0.47303172,  0.72580002,  0.61293721]])

In [12]:
# 生成指定范围的随机数组
n4=np.random.randint(1,3,10) #[1,3)  ,产生10个元素
n4

array([2, 1, 2, 2, 2, 1, 2, 2, 2, 1])

In [13]:
n4=np.random.randint(1,3,size=(2,3)) #[1,3)  
n4

array([[1, 2, 2],
       [2, 1, 1]])

In [14]:
# 生成正态分布 的随机数组
n5=np.random.normal(0,0.1,10)
n5

array([ 0.26432072, -0.01318149,  0.00856988, -0.12897021,  0.03239041,
        0.04059386, -0.13076318,  0.00561303, -0.04215286,  0.01472702])

In [15]:
n5=np.random.normal(0,0.1,size=(2,3))
n5

array([[ 0.06537326, -0.09009622,  0.0888997 ],
       [-0.05705421, -0.12262829,  0.06202712]])

In [23]:
#asarray函数的使用
n1=np.asarray([1,2,3]) # 通过列表创建数组
n1 

array([1, 2, 3])

In [24]:
# 通过列表的元组创建数组
n2=np.asarray([(1,2,3),(4,5,6)])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
# 通过元组创建数组
n3=np.asarray((1,2,3))
n3

array([1, 2, 3])

In [27]:
# 通过元组的元组创建数组
n4=np.asarray(((1,2,3),(3,4,5)))
n4

array([[1, 2, 3],
       [3, 4, 5]])

In [28]:
# 通过元组的列表
n5=np.asarray(([1,2],[4,5]))
n5

array([[1, 2],
       [4, 5]])

In [30]:
# 动态数组
n1=np.frombuffer(b'juanzijie',dtype='S1') # S1表示单个字符串是一个字符
n1

array([b'j', b'u', b'a', b'n', b'z', b'i', b'j', b'i', b'e'], dtype='|S1')

In [32]:
# 从迭代对象中创建数组对象
iter=(i for i in range(5))
n1=np.fromiter(iter,dtype='int')
n1

array([0, 1, 2, 3, 4])

In [33]:
#empty_like的使用
n=np.empty_like([[1,2],[3,4]])  # 创建一个2行2列的数组，因为给定的是2行2列
n

array([[1156566880,        575],
       [         0,          0]])

In [34]:
n=np.zeros_like([[1,2],[3,4]])  # 创建以0填充的2行2列的数组
n

array([[0, 0],
       [0, 0]])

In [35]:
n=np.ones_like([[1,2],[3,4]])  # 创建以1填充的2行2列的数组
n

array([[1, 1],
       [1, 1]])

In [37]:
n=np.full_like([[1,2],[3,4]],8)  # 创建以8填充的2行2列的数组
n

array([[8, 8],
       [8, 8]])