In [4]:
import numpy as np
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n2=np.array([10,10,10])
print(n1)
print(n2)
# 数组的加，减，乘，除
print(np.add(n1,n2))
print(n1+n2)

print('减:',np.subtract(n1,n2))
print('乘:',np.multiply(n1,n2))
print('除:',np.divide(n1,n2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 10 10]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
减: [[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
乘: [[10 20 30]
 [40 50 60]
 [70 80 90]]
除: [[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


In [7]:
# 倒数
n1=np.array([0.25,1.75,2,100])
print(np.reciprocal(n1))

[4.         0.57142857 0.5        0.01      ]


In [8]:
# 幂运算
n1=np.array([10,100,1000])  #n1这个数组的n2次幂
n2=np.array([1,2,3])

print(np.power(n1,n2))


[        10      10000 1000000000]


In [9]:
# 求余
n1=np.array([10,20,30])

n2=np.array([4,5,-8])

print(np.mod(n1,n2))

# 30除以-8的余数 的公式   余=a-n*[a//n]      30//-(8) -3.75向下取整  为  -4   
                             #30-(-8)*(-4)

[ 2  0 -2]


In [15]:
# 四舍五入
n=np.array([1.55,6.823,100,0.11897,3.1415926,-3.456])
print(n)
print(np.around(n)) # 四舍五入取整
print(np.around(n,decimals=2)) # 保留 小数点后2位
print(np.around(n,decimals=-1)) # 四舍五入取整到小数点的左侧

[  1.55        6.823     100.          0.11897     3.1415926  -3.456    ]
[  2.   7. 100.   0.   3.  -3.]
[  1.55   6.82 100.     0.12   3.14  -3.46]
[  0.  10. 100.   0.   0.  -0.]


In [17]:
# 向上取整与向下取整
print(np.ceil(n))
print(np.floor(n))

[  2.   7. 100.   1.   4.  -3.]
[  1.   6. 100.   0.   3.  -4.]


In [19]:
# 三角函数
n=np.array([0,30,45,60,90])
# 不同角度的正弦值
print(np.sin(n*np.pi/180))

print(np.cos(n*np.pi/180))

print(np.tan(n*np.pi/180))

[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
