In [5]:
# 
import numpy as np
n1=np.array([[1,2],[3,4],[5,6]])
# 创建第二个数组
n2=np.array([[10,20],[30,40],[50,60]])
print(n1)
print(n2)

# 水平方向增加数据 (列数的增加)2列， 4列
print(np.hstack((n1,n2)))

#垂直方向增加数据(行数的增加) 3行，变为6行
print(np.vstack((n1,n2)))

[[1 2]
 [3 4]
 [5 6]]
[[10 20]
 [30 40]
 [50 60]]
[[ 1  2 10 20]
 [ 3  4 30 40]
 [ 5  6 50 60]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10 20]
 [30 40]
 [50 60]]


In [9]:
#数组的删除操作
n1=np.array([[1,2],[3,4],[5,6]])
print(n1)

#删除第三行
n2=np.delete(n1,2,axis=0) # 2行索引为2的，轴是0
print(n2)

#删除第一列
n3=np.delete(n1,0,axis=1)
print(n3)

#删除第二行和第三行
n4=np.delete(n1,(1,2),axis=0)
print(n4)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[2]
 [4]
 [6]]
[[1 2]]


In [12]:
#数组的修改操作
n1=np.array([[1,2],[3,4],[5,6]])
print(n1)
#修改操作
n1[1]=[30,40]
print(n1)

n1[2][1]=88
print(n1)

[[1 2]
 [3 4]
 [5 6]]
[[ 1  2]
 [30 40]
 [ 5  6]]
[[ 1  2]
 [30 40]
 [ 5 88]]


In [16]:
#数组的查询操作
n=np.arange(1,11)
print(n)

n2=n[np.where(n>5)] # 数组中所有大于5的元素
print(n2)

n3=np.where(n>5,2,0) # 数组中的元素大于5，输出2,否则输出0
print(n3)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]
[0 0 0 0 0 2 2 2 2 2]
