In [9]:
#
import numpy as np
n=np.arange(6)
print(n)
# 重塑
n1=n.reshape(2,3)
print(n1)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [11]:
n=np.array([[1,2,3],[4,5,6]])
print(n)
n1=n.reshape(3,2)
print(n1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
