In [10]:
import numpy as np
n=np.array([10,20,30,40,50,60,70,80,90])
print(n)

[10 20 30 40 50 60 70 80 90]


In [3]:
print(n[:3]) # 省略起始位置，那么默认从0开始 [0,3), 步长默认为1

[10 20 30]


In [5]:
print(n[3:6]) # [3,6)

[40 50 60]


In [6]:
print(n[6:]) 

[70 80 90]


In [7]:
print(n[6:9])

[70 80 90]


In [8]:
print(n[::]) # 获取数组中的的所有元素

[10 20 30 40 50 60 70 80 90]


In [9]:
#修改步长
print(n[0::2]) # 0,2,4,6,8,

[10 30 50 70 90]


In [11]:
print(n[1::5])

[20 70]


In [12]:
# 步长还可以为负数
print(n[::-1])

[90 80 70 60 50 40 30 20 10]


In [15]:
print(n[-1:-10:-1])

[90 80 70 60 50 40 30 20 10]


In [16]:
print(n[-5:-8:-2])

[50 30]


In [29]:
# 列表的切片操作与数组的切片操作的区别
array=np.array([10,20,30,40])
print(array)
arr1=array[1:4]
print(arr1)
# 对切片之后的数组进行修改
arr1[0]=100
print(arr1)
print(arr)

[10 20 30 40]
[20 30 40]
[100  30  40]
[ 10 100  30  40]


In [32]:
lst=[10,20,30,40]
lst1=lst[1:4]
print(lst1)
lst1[0]=100
print(lst1)
print(lst)

[20, 30, 40]
[100, 30, 40]
[10, 20, 30, 40]


In [37]:
# 二维数组的切片操作
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
print(arr[1,2]) # 1表示的是索引为1的行， 2表示的是索引为2的列

7


In [39]:
print(arr[:2,1:]) # 从索引为0的行到索引为2的行，不包含2，从索引为1的列开始，一直到最后的列

[[2 3 4]
 [6 7 8]]


In [40]:
print(arr[1,:2]) # 逗 号之前表示行，索引为1的行，到索引为2的列结束，不包含2

[5 6]


In [41]:
print(arr[:2,2])

[3 7]


In [42]:
print(arr[:,:1])

[[1]
 [5]
 [9]]
