In [2]:
import numpy as np
n1=np.array([1,2])
n2=np.array([3,4])
print(n1)
print(n2)
# 数组运算
print('加法运算',n1+n2)
print('减法运算',n1-n2)
print('乘法运算',n1*n2)
print('除法运算',n1/n2)
print('幂运算',n1**n2)
print('比较运算',n1>n2)
print('比较运算',n1<n2)
print('比较运算',n1!=n2)

[1 2]
[3 4]
加法运算 [4 6]
减法运算 [-2 -2]
乘法运算 [3 8]
除法运算 [0.33333333 0.5       ]
幂运算 [ 1 16]
比较运算 [False False]
比较运算 [ True  True]
比较运算 [ True  True]


In [24]:
# 数组中的索引
n=np.array([1,2,3,4])
print(n[0])
print(n[-4])

1
1


In [3]:
n=np.array([[1,2,3,4],[5,6,7,8]])
print(n)
print(n[1][2])
print(n[1,2]) # 
print(n[1])
print(n[-1])

[[1 2 3 4]
 [5 6 7 8]]
7
7
[5 6 7 8]
[5 6 7 8]
