In [5]:
import numpy as np
n=np.arange(24).reshape(4,6)
print(n)
# 转置
n2=n.T
print(n2)

# 转置
n3=n.transpose()
print(n3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [8]:
#转置练习
n=np.array([['A',100],['B',200],['C',300],['D',400],['E',500]])
print(n)

newa=n.T
print(newa)

[['A' '100']
 ['B' '200']
 ['C' '300']
 ['D' '400']
 ['E' '500']]
[['A' 'B' 'C' 'D' 'E']
 ['100' '200' '300' '400' '500']]
