In [1]:
#数组的排序
import numpy as np
n=np.array([[4,7,3],[2,8,5],[9,1,6]])
print(n)

[[4 7 3]
 [2 8 5]
 [9 1 6]]


In [2]:
print('数组排序',np.sort(n))

数组排序 [[3 4 7]
 [2 5 8]
 [1 6 9]]


In [3]:
#按行排序
print(np.sort(n,axis=0))

[[2 1 3]
 [4 7 5]
 [9 8 6]]


In [5]:
#按列排序
print(np.sort(n,axis=1))

[[3 4 7]
 [2 5 8]
 [1 6 9]]


In [7]:
#argsort()排序
x=np.array([9,5,3,4,2,1,6,8])
#排序
y=np.argsort(x)
print(y)
#排序后的重构数组
print(x[y])

[5 4 2 3 1 6 7 0]
[1 2 3 4 5 6 8 9]


In [9]:
#lexsort()排序
math=np.array([101,109,115,108,118,118]) # 数学成绩

en=np.array([117,105,118,108,98,109]) # 英语成绩

total=np.array([621,623,620,620,615,615]) # 总成绩

#排序
sort_total=np.lexsort((en,math,total)) # 排序的顺序  总-->数学-->英语

print(sort_total) # 排序后的索引值

lst=[  [total[i],math[i],en[i]   ]for i in sort_total]

n=np.array(lst)
print(n)

[4 5 3 2 0 1]
[[615 118  98]
 [615 118 109]
 [620 108 108]
 [620 115 118]
 [621 101 117]
 [623 109 105]]
