In [4]:
import numpy as np
a=np.mat('5 6;7 8') # 创建矩阵的方式
print(a)

b=np.mat([[5,6],[7,8]])
print(b)

print(type(a),type(b))

n1=np.array([[5,6],[7,8]])
print(type(n1))

[[5 6]
 [7 8]]
[[5 6]
 [7 8]]
<class 'numpy.matrix'> <class 'numpy.matrix'>
<class 'numpy.ndarray'>


In [5]:
# 使用mat函数创建常见的矩阵
#创建一个3*3的零矩阵
d1=np.mat(np.zeros((3,3)))
print(d1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# 创建一个2*4的1矩阵
d2=np.mat(np.ones((2,4)))
print(d2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
nd3=np.mat(np.random.rand(3,3)) # 0-1之间的随机数
print(nd3)

[[0.31778051 0.26456282 0.19043189]
 [0.04446189 0.24296307 0.6318717 ]
 [0.15619671 0.29178315 0.05843207]]


In [8]:
#  1-8之间的随机数
d4=np.mat(np.random.randint(1,8,size=(3,5)))
print(d4)

[[4 7 7 3 1]
 [3 1 5 1 5]
 [3 2 6 2 2]]


In [10]:
# 对角矩阵
nd5=np.mat(np.eye(2,2),dtype=int)
print(nd5)

nd6=np.mat(np.eye(4,4),dtype=int)
print(nd6)

[[1 0]
 [0 1]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [11]:
# 对角线矩阵
a=[1,2,3]
data1=np.mat(np.diag(a))   # 对象线是1，2，3
print(data1)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [12]:
b=[7,8,9]
data1=np.mat(np.diag(b))   # 对象线是7，8，9
print(data1)

[[7 0 0]
 [0 8 0]
 [0 0 9]]
